// USER REDUCER TYPES
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ'

// UI REDUCER TYPES
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// DATA REDUCER TYPES 
export const SET_SAYITS = 'SET_SAYITS'; 
export const SET_SAYIT = 'SET_SAYIT'; 
export const LIKE_SAYIT = 'LIKE_SAYIT';
export const UNLIKE_SAYIT = 'UNLIKE_SAYIT';
export const DELETE_SAYIT = 'DELETE_SAYIT';
export const POST_SAYIT = 'POST_SAYIT';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';